LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

SRC += $(USER_PATH)/main.c

ifeq ($(strip $(TAP_DANCE_ENABLE)), yes)
INTROSPECTION_KEYMAP_C = $(USER_PATH)/introspection_keymap.c
endif
